TestTryCatchFinally = {

	["test: Error in try() is being silent"] = function () error "Not implemented" end; -- TODO
	["test: No errors in try() is silent"] = function () error "Not implemented" end; -- TODO
	["test: Error in try() is being processed in catch()"] = function () error "Not implemented" end; -- TODO
	["test: No errors in try() won't make catch() execute"] = function () error "Not implemented" end; -- TODO
	["test: finally() executes after error in try()"] = function () error "Not implemented" end; -- TODO
	["test: finally() executes after no errors in try()"] = function () error "Not implemented" end; -- TODO
	["test: finally() as expression after error"] = function () error "Not implemented" end; -- TODO
	["test: finally() as expression after no errors"] = function () error "Not implemented" end; -- TODO
}
